apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-was-deployment
  labels:
    node: service
spec:
  replicas: 1 # pod 개수 지정 
  selector:
    matchLabels:
      node: service
  template:
    metadata:
      labels:
        node: service
    spec:
      containers:
      - name: shopping-container
        image: asia.gcr.io/eunoia0523/springshoppingcart:v1 # 아까 자신이 gcr에 업로드한 이미지 
        ports:
        - containerPort: 8080
        resources:
          requests: ## 오토파일럿 모드에서 없으면 에러 발생 
            memory: "100Mi"
            cpu: "250m"
          limits: ## limit이 없으면 오토스케일링 문제 발생  
            cpu: "500m"
      nodeSelector:
        cloud.google.com/gke-nodepool: service-pool
---
apiVersion: v1
kind: Service
metadata:
  name: was-lb
spec:
  type: LoadBalancer
  selector:
    node: service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
